name: check flake8_executable lints

on:
  push:
    branches: ["wsl**"]
  workflow_dispatch:

jobs:
  install_wsl:
    name: "Cache WSL vhdx"
    runs-on: windows-latest
    timeout-minutes: 20
    env:
      CACHE_KEY: "wsl_cache_v2"
      CACHE_FILE: "ubuntu_ruff.vhdx"
      CACHE_DIR: ".wsl_cache"
      DISTRO: "Ubuntu-24.04"
      EXT4_WORKSPACE: "/${{ github.repository }}"
    outputs:
      CACHE_KEY: ${{ env.CACHE_KEY }}
      CACHE_LOCATION: ${{ steps.tmpdir.outputs.CACHE_LOCATION }}
      VHDX_FILE: ${{ steps.tmpdir.outputs.VHDX_FILE }}
      DISTRO: ${{ env.DISTRO }}
      EXT4_WORKSPACE: ${{ env.EXT4_WORKSPACE }}
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - id: tmpdir
        name: "Identify full path to cache"
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $cachePath = Join-Path ${{ runner.temp }} $env:CACHE_DIR
          Write-Output "CACHE_LOCATION=$cachePath"
          Write-Output "CACHE_LOCATION=$cachePath" >> $env:GITHUB_OUTPUT
          $vhdxPath = Join-Path $cachePath $env:CACHE_FILE
          Write-Output "VHDX_FILE=$vhdxPath"
          Write-Output "VHDX_FILE=$vhdxPath" >> $env:GITHUB_OUTPUT
      - id: cache-wsl
        uses: actions/cache@v4
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ steps.tmpdir.outputs.CACHE_LOCATION}}
      - name: "Setup WSL"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        uses: Vampire/setup-wsl@v5
        with:
          distribution: ${{ env.DISTRO }}
          use-cache: 'false'
          additional-packages:
            build-essential
            mold
      - name: "Who am I"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        run: |
          id
          uname -a
      - name: "Filesystems"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        run: |
          df -T
      - name: "Create dir for ext4 workspace"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        run: |
          mkdir --parents ${{ env.EXT4_WORKSPACE }}
      - name: "Install Rust toolchain"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: "Install insta snapshot testing"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        run: |
          curl -LsSf https://insta.rs/install.sh | sh
      - name: "Install nextest"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        run: |
          source $HOME/.cargo/env
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cargo-nextest --secure -y
      - name: "Export distro for cache"
        if: ${{ steps.cache-wsl.outputs.cache-hit != 'true'}}
        shell: pwsh
        env:
          CACHE_LOCATION: ${{ steps.tmpdir.outputs.CACHE_LOCATION }}
          VHDX_FILE: ${{ steps.tmpdir.outputs.VHDX_FILE }}
        run: |
          $ErrorActionPreference = 'Stop'
          wsl --list
          wsl --shutdown
          New-Item -ItemType Directory -Path $env:CACHE_LOCATION -Force
          wsl --export --vhd $env:DISTRO $env:VHDX_FILE
      - name: "Check vhdx file exists"
        id: check
        shell: pwsh
        env:
          VHDX_FILE: ${{ steps.tmpdir.outputs.VHDX_FILE }}
        run: |
            $ErrorActionPreference = 'Stop'
            if (Test-Path $env:VHDX_FILE) {
            exit 0
            } else {
            Write-Error "File not found: $env:VHDX_FILE"
            exit 1
            }
  
  test_wsl_ntfs:
    needs:
      install_wsl
    name: "Run tests on WSL - mounted NTFS filesystem"
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - id: cache-wsl
        uses: actions/cache@v4
        with:
          key: ${{ needs.install_wsl.outputs.CACHE_KEY }}
          path: ${{ needs.install_wsl.outputs.CACHE_LOCATION }}
      - name: "Import cached Distro"
        shell: pwsh
        env:
          VHDX_FILE: ${{ needs.install_wsl.outputs.VHDX_FILE }}
          DISTRO: ${{ needs.install_wsl.outputs.DISTRO }}
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Updating WSL"
          wsl --update
          Write-Output "Importing $env:VHDX_FILE as $env:DISTRO"
          wsl --import-in-place $env:DISTRO $env:VHDX_FILE
      - name: "Setup WSL"
        uses: Vampire/setup-wsl@v5
        with:
          distribution: ${{ needs.install_wsl.outputs.DISTRO }}
          use-cache: 'false'
      - name: "Who am I"
        run: |
          id
          uname -a
      - name: "Working Directory"
        run: |
          pwd
          ls -al
      - name: "Filesystems"
        run: |
          df -T
      - name: "Run tests"
        env:
          NEXTEST_PROFILE: "ci-short"
        run: |
          source $HOME/.cargo/env
          cargo insta test --check --test-runner nextest --package ruff_linter -- flake8_executable

  test_wsl_ext4:
    needs:
      install_wsl
    name: "Run tests on WSL Native filesystem"
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: wsl-bash {0}
    env:
        WORKSPACEDIR: ${{ needs.install_wsl.outputs.EXT4_WORKSPACE }}
    steps:
      - id: cache-wsl
        uses: actions/cache@v4
        with:
          key: ${{ needs.install_wsl.outputs.CACHE_KEY }}
          path: ${{ needs.install_wsl.outputs.CACHE_LOCATION }}
      - name: "Import cached Distro"
        shell: pwsh
        env:
          VHDX_FILE: ${{ needs.install_wsl.outputs.VHDX_FILE }}
          DISTRO: ${{ needs.install_wsl.outputs.DISTRO }}
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Updating WSL"
          wsl --update
          Write-Output "Importing $env:VHDX_FILE as $env:DISTRO"
          wsl --import-in-place $env:DISTRO $env:VHDX_FILE
      - name: "Setup WSL"
        uses: Vampire/setup-wsl@v5
        with:
          distribution: ${{ needs.install_wsl.outputs.DISTRO }}
          use-cache: 'false'
      - name: "Who am I"
        run: |
          id
          uname -a
      - name: "Checkout (manually)"
        # Needs hardening - move ref_name & repository to env var
        env:
          BRANCHNAME: ${{ github.ref_name }}
        run: |
          cd ${{ env.WORKSPACEDIR }}
          git config --global --add safe.directory ${{ env.WORKSPACEDIR }}
          git init ${{ env.WORKSPACEDIR }}
          git remote add origin  https://github.com${{ env.WORKSPACEDIR }}
          git config --local gc.auto 0
          git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +${{ github.sha }}:refs/remotes/origin/${{ env.BRANCHNAME }}
          git sparse-checkout disable
          git config --local --unset-all extensions.worktreeConfig
          git checkout --progress --force -B ${{ env.BRANCHNAME }} refs/remotes/origin/${{ env.BRANCHNAME }}
      - name: "Working Directory"
        run: |
          cd ${{ env.WORKSPACEDIR }}
          pwd
          ls -al
      - name: "Filesystems"
        run: |
          cd ${{ env.WORKSPACEDIR }}
          df -T
      - name: "Run tests"
        env:
          NEXTEST_PROFILE: "ci-short"
        run: |
          cd ${{ env.WORKSPACEDIR }}
          source $HOME/.cargo/env
          cargo insta test --check --test-runner nextest --package ruff_linter -- flake8_executable

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2.7.8
      - name: "Install Rust toolchain"
        run: rustup show
      - name: "Install mold"
        uses: rui314/setup-mold@v1
      - name: "Install cargo nextest"
        uses: taiki-e/install-action@be7c31b6745feec79dec5eb79178466c0670bb2d # v2
        with:
          tool: cargo-nextest
      - name: "Install cargo insta"
        uses: taiki-e/install-action@be7c31b6745feec79dec5eb79178466c0670bb2d # v2
        with:
          tool: cargo-insta
      - name: "Run tests"
        shell: bash
        env:
          NEXTEST_PROFILE: "ci-short"
        run: cargo insta test --check --test-runner nextest --package ruff_linter -- flake8_executable