# This workflow will check flake8_executable lints on:
# - Native Linux
# - WSL, using an ext4 filesystem
# - WSL, using a windows filesystem
#
# This is to ensure that EXE001 & EXE002 are automatically disabled
# where appropriate.
#
# It will run when:
# - this file is changed or
# - any of the flake8_executable code, tests, fixtures, ... are changed.
#
# On first run it will cache the installed WSL distro, as the initial
# installation is time-consuming.

name: Check flake8_executable lints

on:
  push:
    paths:
      [
        ".github/workflows/test_flake8_executable_wsl.yml",
        ".github/actions/cache-wsl-distro/action.yml",
        "**/flake8_executable/**",
      ]
  workflow_dispatch:

permissions: {}

jobs:
  find_wsl_cache:
    name: "Check/Create WSL vhdx"
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      CACHE_FILE: "ubuntu_ruff.vhdx"
      CACHE_DIR: ".wsl_cache"
      DISTRO: "Ubuntu"
      EXT4_WORKSPACE: "/workspaces/${{ github.repository }}"
    outputs:
      cache_key: ${{ steps.calc_vars.outputs.cache_key }}
      cache_path: ${{ steps.calc_vars.outputs.cache_path }}
      vhdx_file: ${{ steps.calc_vars.outputs.vhdx_file }}
      distro: ${{ env.DISTRO }}
      ext4_workspace: ${{ env.EXT4_WORKSPACE }}
    steps:
      # Using version numbers, not SHAs, throughout to avoid dependabot triggering this workflow often
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - id: calc_vars
        name: "Calculate paths & key"
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $cachePath = Join-Path ${{ runner.temp }} $env:CACHE_DIR
          Write-Output "cache_path=$cachePath"
          Write-Output "cache_path=$cachePath" >> $env:GITHUB_OUTPUT
          $vhdxPath = Join-Path $cachePath $env:CACHE_FILE
          Write-Output "vhdx_file=$vhdxPath"
          Write-Output "vhdx_file=$vhdxPath" >> $env:GITHUB_OUTPUT
          $workflowHash = (Get-FileHash .github/actions/cache-wsl-distro/action.yml).Hash
          Write-Output "cache_key=wsl_distro_cache-$workflowHash"
          Write-Output "cache_key=wsl_distro_cache-$workflowHash" >> $env:GITHUB_OUTPUT
      - id: check-wsl-cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.calc_vars.outputs.cache_key }}
          path: ${{ steps.calc_vars.outputs.cache_path}}
          lookup-only: true
      - name: "Create and cache distro"
        if: ${{ steps.check-wsl-cache.outputs.cache-hit != 'true'}}
        uses: ./.github/actions/cache-wsl-distro
        with:
          cache_key: ${{ steps.calc_vars.outputs.cache_key }}
          cache_path: ${{ steps.calc_vars.outputs.cache_path }}
          vhdx_file: ${{ steps.calc_vars.outputs.vhdx_file }}
          distro: ${{ env.DISTRO }}
          ext4_workspace: ${{ env.EXT4_WORKSPACE }}

  test_wsl_ntfs:
    needs: find_wsl_cache
    name: "Run tests on WSL - mounted NTFS filesystem"
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: "Get wsl distro from cache"
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.find_wsl_cache.outputs.cache_key }}
          path: ${{ needs.find_wsl_cache.outputs.cache_path }}
          fail-on-cache-miss: true
      - name: "Import cached Distro"
        id: import-wsl
        shell: pwsh
        env:
          VHDX_FILE: ${{ needs.find_wsl_cache.outputs.vhdx_file }}
          DISTRO: ${{ needs.find_wsl_cache.outputs.distro }}
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Updating WSL"
          wsl --update
          Write-Output "Importing $env:VHDX_FILE as $env:DISTRO"
          wsl --import-in-place $env:DISTRO $env:VHDX_FILE

          # We use this --cd trick otherwise bash gets confused with the \ path separators
          $workspacePath = wsl.exe -d $env:DISTRO --cd $env:GITHUB_WORKSPACE -- wslpath -ua .
          Write-Output "WSL Path to Workspace: $workspacePath"
          Write-Output "workspace_path=$workspacePath" >> $env:GITHUB_OUTPUT
      # Using the wsl-native filesystem for storing build artifacts reduces build from 10 mins to 3 mins
      - name: "Use wsl-native file system for ./target"
        uses: ubuntu/WSL/.github/actions/wsl-bash@main
        with:
          distro: ${{ needs.find_wsl_cache.outputs.distro }}
          working-dir: ${{ steps.import-wsl.outputs.workspace_path }}
          exec: |
            mkdir /tmp/target
            mkdir target || true
            mount --bind /tmp/target target
      - name: "Run tests"
        uses: ubuntu/WSL/.github/actions/wsl-bash@main
        with:
          distro: ${{ needs.find_wsl_cache.outputs.distro }}
          working-dir: ${{ steps.import-wsl.outputs.workspace_path }}
          exec: |
            source $HOME/.cargo/env
            export NEXTEST_PROFILE="ci-short"
            RUFF_TEST_ENVIRONMENT="ntfs" cargo insta test --check --test-runner nextest --package ruff_linter -- flake8_executable

  test_wsl_ext4:
    needs: find_wsl_cache
    name: "Run tests on WSL Native filesystem"
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: "Get wsl distro from cache"
        uses: actions/cache/restore@v4
        with:
          key: ${{ needs.find_wsl_cache.outputs.cache_key }}
          path: ${{ needs.find_wsl_cache.outputs.cache_path }}
          fail-on-cache-miss: true
      - name: "Import cached Distro"
        shell: pwsh
        env:
          VHDX_FILE: ${{ needs.find_wsl_cache.outputs.vhdx_file }}
          DISTRO: ${{ needs.find_wsl_cache.outputs.distro }}
        run: |
          $ErrorActionPreference = 'Stop'
          Write-Output "Updating WSL"
          wsl --update
          Write-Output "Importing $env:VHDX_FILE as $env:DISTRO"
          wsl --import-in-place $env:DISTRO $env:VHDX_FILE
      - name: Checkout
        uses: ubuntu/WSL/.github/actions/wsl-checkout@main
        with:
          distro: ${{ needs.find_wsl_cache.outputs.distro }}
          working-dir: ${{ needs.find_wsl_cache.outputs.ext4_workspace }}
      - name: "Run tests"
        uses: ubuntu/WSL/.github/actions/wsl-bash@main
        with:
          distro: ${{ needs.find_wsl_cache.outputs.distro }}
          working-dir: ${{ needs.find_wsl_cache.outputs.ext4_workspace }}
          exec: |
            source $HOME/.cargo/env
            export NEXTEST_PROFILE="ci-short"
            cargo insta test --check --test-runner nextest --package ruff_linter -- flake8_executable

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: Swatinem/rust-cache@v2
      - name: "Install Rust toolchain"
        run: rustup show
      - name: "Install mold"
        uses: rui314/setup-mold@v1
      - name: "Install cargo nextest"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: "Install cargo insta"
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-insta
      - name: "Run tests"
        shell: bash
        env:
          NEXTEST_PROFILE: "ci-short"
        run: cargo insta test --check --test-runner nextest --package ruff_linter -- flake8_executable
