name: Test_on_WSL

on:
- push

jobs:
  install_wsl:
    name: "Install WSL"
    runs-on: windows-latest
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
      - name: "Setup WSL"
        uses: Vampire/setup-wsl@v5
        with:
          distribution: Ubuntu-24.04

      - name: "Who am I"
        run: |
          id
          uname -a

      - name: "Working Directory"
        run: |
          pwd
          ls -al
      
      - name: "Filesystems"
        run: |
          df -T

      - name: "Install gcc & mold"
        run: |
          apt update
          apt install -y build-essential mold

      - name: "Install Rust toolchain"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: "Install insta snapshot testing"
        run: |
          curl -LsSf https://insta.rs/install.sh | sh

      - name: "Install nextest"
        run: |
          source $HOME/.cargo/env
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall cargo-nextest --secure -y

      - name: "Checkout repo"
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
          ls -al

      - name: "ls -al exe tests"
        run : |
          ls -al crates/ruff_linter/resources/test/fixtures/flake8_executable
          ls -al crates/ruff_linter/src/rules/flake8_executable/snapshots
      
      # - name: "Run tests"
      #   env:
      #     NEXTEST_PROFILE: "ci"
      #   run: |
      #     source $HOME/.cargo/env
      #     cargo insta test --all-features --unreferenced reject --test-runner nextest
 